steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --platform=managed
      - --port=8080
      - --allow-unauthenticated
      - --min-instances=0
      - --max-instances=10
      - --memory=1Gi
      - --cpu=1
      - --timeout=300

images:
  - ${_IMAGE}

substitutions:
  _REGION: asia-south1
  _REPOSITORY: mlsc
  _SERVICE: mlsc-timetable-backend
  _IMAGE: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
